# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator_mine.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(443, 732)
        Form.setMinimumSize(QtCore.QSize(443, 732))
        Form.setStyleSheet("QFrame{\n"
"    background-color:rgb(0, 0, 0);\n"
"}\n"
"#button_frame{\n"
"    border-bottom: 1px solid black;\n"
"    border-radius:15px;\n"
"}\n"
"#button_frame QLineEdit{\n"
"    background-color:#000000;\n"
"    color:#FFF;\n"
"    border:none;\n"
"    hight:50px;\n"
"    padding:10px 5px;\n"
"    font-size: 70px;\n"
"    font-family:\"Segoe UI\";\n"
"}\n"
"#button_frame QPushButton{\n"
"    background-color:#333333;\n"
"    color:#FFF;\n"
"    font-size:30px;\n"
"    font-family:\"Helvetica\";\n"
"    border-radius: 50%;\n"
"    width    :100px;\n"
"    height:100px;\n"
"}\n"
"#button_frame QPushButton:pressed{\n"
"    background-color:#555;\n"
"}\n"
"#button_frame #zero_btn {\n"
"    text-align:centert;\n"
"\n"
"}\n"
"\n"
"#button_frame QPushButton[class=\"btn_group_1\"]{\n"
"    border-radius:50%;\n"
"    font-size:30px;\n"
"    background-color:#a5a5a5;\n"
"    color:#020202;\n"
"}\n"
"#button_frame QPushButton[class=\"btn_group_1\"]:pressed{\n"
"    background-color:#d6d6d6;\n"
"    \n"
"}\n"
"\n"
"#button_frame QPushButton[class=\"btn_group_2\"]{\n"
"    background-color:#ca3401;\n"
"    font-size:30px;\n"
"}\n"
"\n"
"#button_frame QPushButton[class=\"btn_group_2\"]:checked,\n"
"#button_frame QPushButton[class=\"btn_group_2\"]:pressed{\n"
"    background-color:#fff;\n"
"\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_frame = QtWidgets.QFrame(Form)
        self.button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_frame.setObjectName("button_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.button_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.button_frame)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.Ans_LineEdit = QtWidgets.QLineEdit(self.button_frame)
        self.Ans_LineEdit.setEnabled(False)
        self.Ans_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Ans_LineEdit.setObjectName("Ans_LineEdit")
        self.verticalLayout.addWidget(self.Ans_LineEdit)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 4)
        self.claer_btn = QtWidgets.QPushButton(self.button_frame)
        self.claer_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.claer_btn.setAutoFillBackground(False)
        self.claer_btn.setObjectName("claer_btn")
        self.gridLayout.addWidget(self.claer_btn, 1, 0, 1, 1)
        self.plus_minus_btn = QtWidgets.QPushButton(self.button_frame)
        self.plus_minus_btn.setObjectName("plus_minus_btn")
        self.gridLayout.addWidget(self.plus_minus_btn, 1, 1, 1, 1)
        self.percentage_btn = QtWidgets.QPushButton(self.button_frame)
        self.percentage_btn.setObjectName("percentage_btn")
        self.gridLayout.addWidget(self.percentage_btn, 1, 2, 1, 1)
        self.division_btn = QtWidgets.QPushButton(self.button_frame)
        self.division_btn.setObjectName("division_btn")
        self.gridLayout.addWidget(self.division_btn, 1, 3, 1, 1)
        self.seven_btn = QtWidgets.QPushButton(self.button_frame)
        self.seven_btn.setObjectName("seven_btn")
        self.gridLayout.addWidget(self.seven_btn, 2, 0, 1, 1)
        self.eight_btn = QtWidgets.QPushButton(self.button_frame)
        self.eight_btn.setObjectName("eight_btn")
        self.gridLayout.addWidget(self.eight_btn, 2, 1, 1, 1)
        self.nine_btn = QtWidgets.QPushButton(self.button_frame)
        self.nine_btn.setObjectName("nine_btn")
        self.gridLayout.addWidget(self.nine_btn, 2, 2, 1, 1)
        self.multi_btn = QtWidgets.QPushButton(self.button_frame)
        self.multi_btn.setObjectName("multi_btn")
        self.gridLayout.addWidget(self.multi_btn, 2, 3, 1, 1)
        self.four_btn = QtWidgets.QPushButton(self.button_frame)
        self.four_btn.setStyleSheet("")
        self.four_btn.setObjectName("four_btn")
        self.gridLayout.addWidget(self.four_btn, 3, 0, 1, 1)
        self.five_btn = QtWidgets.QPushButton(self.button_frame)
        self.five_btn.setObjectName("five_btn")
        self.gridLayout.addWidget(self.five_btn, 3, 1, 1, 1)
        self.six_btn = QtWidgets.QPushButton(self.button_frame)
        self.six_btn.setObjectName("six_btn")
        self.gridLayout.addWidget(self.six_btn, 3, 2, 1, 1)
        self.plus_btn = QtWidgets.QPushButton(self.button_frame)
        self.plus_btn.setObjectName("plus_btn")
        self.gridLayout.addWidget(self.plus_btn, 3, 3, 1, 1)
        self.one_btn = QtWidgets.QPushButton(self.button_frame)
        self.one_btn.setObjectName("one_btn")
        self.gridLayout.addWidget(self.one_btn, 4, 0, 1, 1)
        self.two_btn = QtWidgets.QPushButton(self.button_frame)
        self.two_btn.setObjectName("two_btn")
        self.gridLayout.addWidget(self.two_btn, 4, 1, 1, 1)
        self.three_btn = QtWidgets.QPushButton(self.button_frame)
        self.three_btn.setObjectName("three_btn")
        self.gridLayout.addWidget(self.three_btn, 4, 2, 1, 1)
        self.minus_btn = QtWidgets.QPushButton(self.button_frame)
        self.minus_btn.setObjectName("minus_btn")
        self.gridLayout.addWidget(self.minus_btn, 4, 3, 1, 1)
        self.ans_btn = QtWidgets.QPushButton(self.button_frame)
        self.ans_btn.setObjectName("ans_btn")
        self.gridLayout.addWidget(self.ans_btn, 5, 2, 1, 1)
        self.equal_btn = QtWidgets.QPushButton(self.button_frame)
        self.equal_btn.setObjectName("equal_btn")
        self.gridLayout.addWidget(self.equal_btn, 5, 3, 1, 1)
        self.zero_btn = QtWidgets.QPushButton(self.button_frame)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        self.zero_btn.setFont(font)
        self.zero_btn.setObjectName("zero_btn")
        self.gridLayout.addWidget(self.zero_btn, 5, 0, 1, 1)
        self.dot_btn = QtWidgets.QPushButton(self.button_frame)
        self.dot_btn.setObjectName("dot_btn")
        self.gridLayout.addWidget(self.dot_btn, 5, 1, 1, 1)
        self.gridLayout_2.addWidget(self.button_frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setText(_translate("Form", ""))
        self.Ans_LineEdit.setText(_translate("Form", "=0"))
        self.claer_btn.setText(_translate("Form", "AC"))
        self.claer_btn.setProperty("class", _translate("Form", "btn_group_1"))
        self.plus_minus_btn.setText(_translate("Form", "+/-"))
        self.plus_minus_btn.setProperty("class", _translate("Form", "btn_group_1"))
        self.percentage_btn.setText(_translate("Form", "%"))
        self.percentage_btn.setProperty("class", _translate("Form", "btn_group_1"))
        self.division_btn.setText(_translate("Form", "÷"))
        self.division_btn.setProperty("class", _translate("Form", "btn_group_2"))
        self.seven_btn.setText(_translate("Form", "7"))
        self.eight_btn.setText(_translate("Form", "8"))
        self.nine_btn.setText(_translate("Form", "9"))
        self.multi_btn.setText(_translate("Form", "x"))
        self.multi_btn.setProperty("class", _translate("Form", "btn_group_2"))
        self.four_btn.setText(_translate("Form", "4"))
        self.five_btn.setText(_translate("Form", "5"))
        self.six_btn.setText(_translate("Form", "6"))
        self.plus_btn.setText(_translate("Form", "+"))
        self.plus_btn.setProperty("class", _translate("Form", "btn_group_2"))
        self.one_btn.setText(_translate("Form", "1"))
        self.two_btn.setText(_translate("Form", "2"))
        self.three_btn.setText(_translate("Form", "3"))
        self.minus_btn.setText(_translate("Form", "-"))
        self.minus_btn.setProperty("class", _translate("Form", "btn_group_2"))
        self.ans_btn.setText(_translate("Form", "Ans"))
        self.equal_btn.setText(_translate("Form", "="))
        self.equal_btn.setProperty("class", _translate("Form", "btn_group_2"))
        self.zero_btn.setText(_translate("Form", "0"))
        self.dot_btn.setText(_translate("Form", "."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
